project:
  type: website
  output-dir: docs
  
website:
  title: "About Me"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Hobbies.qmd
      - Reflection.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left


